alert('What The most thing that you interseted about IOT ?');



var newtechnology= prompt("What is the best technology?");


if(newtechnology=='VR'){
    document.write('<div><img src="picture/VR.jpg" alt="robot" ></div>');
}else if(newtechnology=='robot'){
    document.write('<div><img src="picture/robot.jpg" alt="VR" ></div>');
}else{
    alert("Next time be sure more about it");
  }


alert('What The most thing that you interseted about IOT ?');


var IOT=true;


if(IOT==true){
  console.log('new technology');
}
else{
   console.log('actullay it is new tech with AI');
 }