


alert("Hi in my sweets website")

var sweets = prompt("Choics cookies or bakery?");

if (sweets == 'cookies') {
    document.write('<div><img src="picture/COOKIES.jpg" alt="cookies" ></div>');
} else if (sweets == 'bakery') {
    document.write('<div><img src="picture/BAKERY2.jpg" alt="bakery" ></div>');
} else {
    alert("Next time be sure more about it");
}
alert("Thanks for your visit")

 var ar = prompt('Whatis your  the fav sweet ?');
 
 document.write('<h2>'+ ar +'</h2>');


var Sweet = true;


if (Sweet == true) {
    console.log('new ');
}
else {
    console.log('Be sure ');
}